### ISSUE TITLE
"Loading error: need more than 1 value to unpack:loading"

### ISSUE THREAD

**Issue by wfsandoval12** [klen/graphite-beacon#126]
Beginner with graphite. Working on project that uses graphite to monitor performance/load tests. Need graphite-beacon to send alert/email when a given metric crosses a threshold. I am getting the following error:

![error](https://cloud.githubusercontent.com/assets/20544483/16963306/7509d254-4dbb-11e6-8635-51f88ee81995.PNG)

Here is the alert part of my config.json file. I am fairly certain my smtp part is working.

  "alerts": [
    {
      "name": "RQS",
      "query": "aliasByNode(sumSeriesWithWildcards(gatling.membersimulation.AddMemberAddress.all.min, 3), 1)",
      "format": "short",
      "interval": "30second",
      "source": "graphite",
      "method": "average",
      "rules": ["critical: != 200"]
    }

  ]

**Comment by garrettheel** [comment]
If you could run a dev copy of graphite-beacon and log the full stack trace that would help greatly. Unfortunately we don't log enough in this instance to reveal the issue easily

**Comment by garrettheel** [comment]
FWIW, I ran into something similar locally during development and it's probably the same issue you're hitting here. It's during the instantiation of `GraphiteRecord` and happens when the data in the HTTP response is not valid. You might want to load the URL manually and check that there's a response.

I'll add a peek at the data to the error message to help debug this in future.
